### ISSUE TITLE
Search is not working...!!

### ISSUE THREAD

**Issue by navjot369** [Sumanyu301/Recipe_sharing_website-#1]
<img width="1323" alt="Screenshot 2024-03-13 at 8 05 19 PM" src="https://github.com/Sumanyu301/Recipe_sharing_website-/assets/109858950/b1117139-1ab7-45eb-a29f-89fc5f87e359">

**Comment by Sumanyu301** [comment]
it works.

**Comment by navjot369** [comment]
Yess, it is...my bad...!!
